export const dogBreeds = [
    "Labrador Retriever",
    "German Shepherd",
    "Golden Retriever",
    "Bulldog",
    "Beagle",
    "Poodle",
    "French Bulldog",
    "Yorkshire Terrier",
    "Boxer",
    "Dachshund",
    "Siberian Husky",
    "Doberman Pinscher",
    "Great Dane",
    "Shih Tzu",
    "Rottweiler",
    "Pomeranian",
    "Chihuahua",
    "Border Collie",
    "Shetland Sheepdog",
    "Cavalier King Charles Spaniel",
    "Australian Shepherd",
    "Basset Hound",
    "Weimaraner",
    "Maltese",
    "Bernese Mountain Dog",
    "Boston Terrier",
    "Cocker Spaniel",
    "Pug",
    "Saint Bernard",
    "Miniature Schnauzer",
    "Shiba Inu",
    "Pembroke Welsh Corgi",
    "Vizsla",
    "Collie",
    "Papillon",
    "Bloodhound",
    "Newfoundland",
    "Irish Setter",
    "English Springer Spaniel",
    "Havanese",
    "West Highland White Terrier",
    "Bichon Frise",
    "Akita",
    "Whippet",
    "Chinese Shar-Pei",
    "Alaskan Malamute",
];
